---
-- Created by IntelliJ IDEA.
-- User: ZenX2
-- Date: 1/7/12
-- Time: 11:07 PM
--

--T O D O | L I S T

--TODO: Devise physics. DONE
--TODO: Fix sprite loader DONE
--TODO: Get map loader working IN PROGRESS
--TODO:

--Interesting color palette
--[[
#####  Color Palette by Color Scheme Designer
#####  Palette URL: http://colorschemedesigner.com/#2F51K--mmK-eb
#####  Color Space: RGB;



*** Primary Color:

   var. 1 = #369B00 = rgb(54,155,0)
   var. 2 = #396124 = rgb(57,97,36)
   var. 3 = #1A4A00 = rgb(26,74,0)
   var. 4 = #4BB114 = rgb(75,177,20)
   var. 5 = #55B123 = rgb(85,177,35)

*** Secondary Color A:

   var. 1 = #007E3A = rgb(0,126,58)
   var. 2 = #1E4F34 = rgb(30,79,52)
   var. 3 = #003C1C = rgb(0,60,28)
   var. 4 = #119B51 = rgb(17,155,81)
   var. 5 = #1F9B58 = rgb(31,155,88)

*** Secondary Color B:

   var. 1 = #71A700 = rgb(113,167,0)
   var. 2 = #536827 = rgb(83,104,39)
   var. 3 = #364F00 = rgb(54,79,0)
   var. 4 = #85BA15 = rgb(133,186,21)
   var. 5 = #8ABA25 = rgb(138,186,37)


#####  Generated by Color Scheme Designer (c) Petr Stanicek 2002-2010

GPL (gimp) palette

GIMP Palette
Name: Color Palette by Color Scheme Designer #2F51K--mmK-ebColumns: 4

#
 54 155   0     primary 1
 57  97  36     primary 2
 26  74   0     primary 3
 75 177  20     primary 4
 85 177  35     primary 5
  0 126  58     secondary-a 1
 30  79  52     secondary-a 2
  0  60  28     secondary-a 3
 17 155  81     secondary-a 4
 31 155  88     secondary-a 5
113 167   0     secondary-b 1
 83 104  39     secondary-b 2
 54  79   0     secondary-b 3
133 186  21     secondary-b 4
138 186  37     secondary-b 5]]